### ISSUE TITLE
imfile to send apache logs to remote syslog not working

### ISSUE THREAD

**Issue by juju4** [voxpupuli/puppet-rsyslog#102]
Trying to configure rsyslog to forward to remote syslog, apache logs from file
rsyslog doc from https://www.rsyslog.com/doc/v8-stable/configuration/modules/imfile.html

but it seems most of imfile options are not recognized and no example is provided in forge readme

Only imfile reference that I found in puppet module is in acceptance test
https://github.com/voxpupuli/puppet-rsyslog/blob/4896d5d5a333c96327a14d3fcb33239edc4fb32e/spec/acceptance/inputs_spec.rb
so not sure what is filtering out other options

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.1
- Ruby: 2.4.1
- Distribution: Ubuntu 18.04 (rsyslogd 8.32)
- Module version: 3.2.0

## How to reproduce (e.g Puppet code you use)

```
  class { 'rsyslog::server':
    global_config   => {
        'umask' => {
            'value' => '0022',
            'type' => legacy,
            'priority' => 01, 
        },  
        'PrivDropToUser' => {
            'value' => 'syslog',
            'type' => legacy,
        },  
        'PrivDropToGroup' => {
            'value' => 'syslog',
            'type' => legacy,
        },  
        'workDirectory' => {
            'value' => '/var/spool/rsyslog',
        },  
        'maxMessageSize' => {
            'value' => '64k',
        }   
    },  
   inputs => {
        imfile => {
            type        => "imfile",
            config      => {
              File => "${apache_logdir}/access*log",
#              Tag  => 'apache-access:',
#              StateFile => 'stat-apache-access',
#              Severity => 'info',
#              PersistStateInterval => 20000,
#              Ruleset   => "remoteapachelog",
            }
        }
    },
    rulesets    => {
        remoteapachelog => {
            parameters => {
                'queue.filename' => 'QueueApache',
                'queue.type' => 'LinkedList',
                'queue.spoolDirectory' => "/var/log/rsyslog/queue",
                'queue.size' => 10000,
                'queue.maxdiskspace' => '1000G',
                'queue.timeoutqueue' => 3,
                'queue.dequeuebatchsize' => 1000,
                'queue.saveonshutdown' => 'on',
                'queue.timeoutenqueue' => 0,
                'action.resumeRetryCount' => -1,
            },
            rules      => [
                action => {
                    name    => 'testApache',
                    facility => "*.*",
                    config => {
                        type    => 'omfwd',
                        target  => 'remotelogserver2.local',
                        port    => 514,
                        protocol => 'tcp',
                    },
                }
            ],
        }
    }
  }
```

## What are you seeing

```
       Error: Evaluation Error: Resource type not found: Ruleset (file: /tmp/kitchen/manifests/site.pp, line: 243, column: 15) on node d3ef8b5697ea
```

## What behaviour did you expect instead

normal successful execution

**Comment by itbane** [comment]
Could you remove the other content from your site.pp and run the code again? The error message references line 243. With the snippet you pasted, we can't see if the error even happens here.

We do the same thing within our environment, but configure from hiera (working):

rsyslog::server::inputs:
  imfile_apache_error:
    priority: 21
    confdir: '/etc/rsyslog.d/'
    target: '21-apache-inputs.conf'
    type: imfile
    config:
      file:     '/var/log/apache2/error.log'
      tag:      'apache2-error:'
      severity: 'error'
      facility: 'local6'
      ruleset:  'localLogsToLogserv'
  imfile_apache_access:
    priority: 21
    confdir: '/etc/rsyslog.d/'
    target: '21-apache-inputs.conf'
    type: imfile
    config:
      file:     '/var/log/apache2/access.log'
      tag:      'apache2-access:'
      severity: 'info'
      facility: 'local6'
      ruleset:  'localLogsToLogserv'
rsyslog::server::rulesets:
  localLogsToLogserv:
    target: '41-client-rulesets.conf'
    parameters:
      queue.dequeuebatchsize: '1000'
... some queue parameters ...
      queue.workerthreads: '4'
    rules:
      - action:
          name: localLogsToLogserv
          type: "omrelp"
          config:
            Target: "logserver.internal"
            Port: "1514"
            Template: "tplLogID"
            action.ResumeRetryCount: "-1"

**Comment by dhollinger** [comment]
@juju4 As of now anything inside of the top level parameter name _must be quoted_. When you leave them unquoted, puppet thinks those are native types, when in reality it's just a nested Puppet Hash that is read in by a defined type, formatted with a template and added to the configuration file. 

It's really, really important to note that YAML files usually don't require that strings be wrapped in quotes, but the same does not apply to a Puppet Hash:

Correct code:
``` puppet
inputs => {
        'imfile' => {
            'type'        => "imfile",
            'config'      => {
              'File' => "${apache_logdir}/access*log",
              'Tag'  => 'apache-access:',
              'StateFile' => 'stat-apache-access',
              'Severity' => 'info',
              'PersistStateInterval' => 20000,
              'Ruleset'   => "remoteapachelog",
            }
        }
    },
```

**Comment by juju4** [comment]
Thanks @itbane @dhollinger for the useful feedback.
I managed to fix my configuration. And not hiera because simple travis puppet apply for my testing.
