### ISSUE TITLE
puppet-rsyslog won't install on Puppet Open Source 6

### ISSUE THREAD

**Issue by riches-cg** [voxpupuli/puppet-rsyslog#131]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
puppet6-release-6.0.0-5.el7.noarch
puppetserver-6.5.0-1.el7.noarch
puppet-agent-6.8.1-1.el7.x86_64

- Ruby:
default included in Puppet 6

- Distribution:
CentOS Linux release 7.6.1810 (Core) 

- Module version:
3.3.0

## How to reproduce (e.g Puppet code you use)
puppet module install puppet-rsyslog --version 3.3.0

## What are you seeing
module fails to install due to dependency problem

## What behaviour did you expect instead
successful installation

## Output log
[root@host ~]# puppet module install puppet-rsyslog --version 3.3.0
Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppet.com ...
Error: Could not install module 'puppet-rsyslog' (???)
  No version of 'puppet-rsyslog' can satisfy all dependencies
    Use `puppet module install --ignore-dependencies` to install only this module
[root@host ~]# 

## Any additional information you'd like to impart
We have a clean Puppet 6 installation (no upgrades from earlier installs)
Here is the dependency list:
    puppetlabs-stdlib (>= 1.0.0 < 6.0.0)
    puppetlabs-concat (>= 2.0.0 < 6.0.0)
    puppetlabs-apt (>= 5.0.0 < 7.0.0) 

stdlib must be less than 6.0.0 for this module to install.  This will break on clean installations of Puppet 6.  Don't know about the other dependencies....

**Comment by dhollinger** [comment]
This issue is fixed in puppet-rsyslog >= 4.0.0

Unfortunately, we generally don't backport fixes into old versions
