### ISSUE TITLE
No way to not use hiera and how to create a separate configuration file per service?

### ISSUE THREAD

**Issue by DDEFISHER** [voxpupuli/puppet-rsyslog#138]
This is not a bug but a general design question of the module so I left out the issue template.

It is not clear how or if I can 1) create a separate configuration file per service 2) not use hiera.

I would like to be able to not use hiera to declare classes if possible. This seems to be an issue because there is only one public class to be used which is rsyslog::client::global_config. I could use that in a regular puppet manifest but not really because I would get duplicate class declarations if I wanted to create a profile for each rsyslog service to be monitored (which I would like to do so I can have a base profile that is always applied).

Basically I would like to do the following (not exactly this because obviously this would cause a duplicate class declaration)

```
# profile::rsyslog::base.pp
# this class would end up on every node
class profile::rsyslog::base{

  class { 'rsyslog::client::global_config':
    # base rsyslog config that should be on every host
  }
}
```
```
# profile::rsyslog::haproxy.pp
# this class would end up on nodes with haproxy role
class profile::rsyslog::haproxy{

  class { 'rsyslog::client::global_config':
    # rsyslog config for haproxy in a seperate config file than the base stuff(same file would be better than using hiera but I don't think that is possible here either without using hiera)
  }
}
```
```
# data/common.yaml
---
classes:
  -profile::rsyslog::base
```
```
# roles/haproxy.yaml
---
classes:
  -profile::rsyslog::haproxy

```

Am I missing something and is something like this possible? Take my opinion with a grain of salt because I am newish to puppet and very new to rsyslog but it seems this puppet module could use a define such as rsyslog::client::custom_service that lets you add separate config files per service.

**Comment by dhollinger** [comment]
`rsyslog::client::global_config` isn't a class though, it's a parameter in the `rsyslog::client` class. In reality, to do what you want, you'd need to utilize the `rsyslog::component::global_config` defined type to add your config the way you want, but you'd need to manage how to include the base rsyslog classes as those defined types don't currently include those.

It's also important to note that with the next major release (coming soon), the server/client model is being dropped entirely and there will only be a `rsyslog::config` class replacing them. New documentation will be accompanying the release as well.

**Comment by DDEFISHER** [comment]
Ah right sorry about that my examples should have been something like this.

```
class profile::rsyslog::base{

  class { 'rsyslog::client':
    # base rsyslog config that should be on every host
  }
}
```
