### ISSUE TITLE
Cannot set syslog conf file and directory permissions

### ISSUE THREAD

**Issue by jdwhited** [voxpupuli/puppet-rsyslog#150]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:  agent 6.4.3  (Puppet Enterprise 2019.1)
- Ruby:
- Distribution:  RHEL 7,8
- Module version:  4.0.0 (appears to be an issue in 5.0.0 as well)

## How to reproduce (e.g Puppet code you use)
include rsyslog::client

## What are you seeing
/etc/rsyslog.conf, /etc/rsyslog.d, /etc/rsyslog.d permissions cannot be set
We use 0600 on our files, but can't set that.

## What behaviour did you expect instead
Conf file Permissions exposed as a parameter

**Comment by dhollinger** [comment]
I will look at making the conf file permissions configurable via an init.pp parameter.
