### ISSUE TITLE
rsyslog::base does not restart service

### ISSUE THREAD

**Issue by decibelhertz** [voxpupuli/puppet-rsyslog#154]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.19
- Ruby: 2.4.9
- Distribution: CentOS 7
- Module version: 5.0.0

## How to reproduce (e.g Puppet code you use)

populate the `rsyslog::feature_packages` variable after managing rsyslog service with this module

## What are you seeing

When I populate the `rsyslog::feature_packages` variable, it does not restart the (managed) rsyslog service.  Looking at `rsyslog::base`, there is a lot of conditional logic that makes that challenging to ensure.

## What behaviour did you expect instead

If I am installing packages, its likely that I want that change to restart the service.  Suggest a refactor of `rsyslog::base` into `rsyslog::install` and `rsyslog::service` so that one class can notify the other from `init.pp`. EG https://github.com/puppetlabs/puppetlabs-ntp/tree/master/manifests

## Any additional information you'd like to impart
I am willing to do a PR.

**Comment by dhollinger** [comment]
@decibelhertz After a discussion with the team, automatically restarting the service on a package change is not a common process followed by most of our users and thus we consider it an anti-pattern.

In the example you linked, the common practice is to have the install chain into the config and the config class(es) notify the service. In that example, the _only_ time the service would be restarted is if something in the config class changes. We already do this in rsyslog.

**Comment by decibelhertz** [comment]
Yes, I noticed the same thing after submitting my comment.  That said, while I can accept the answer given, I will mention that I think this case was/is a touch different.  

This is because rsyslog will generate a startup error if one declares certain modules active in the configuration if that module is not installed.  The fix is to add the needed package(s) to `rsyslog::feature_packages` and restart the service with no change in configuration.  So, my thinking is that `rsyslog::feature_packages` blurs the line between installation and configuration as its an add-on package(s) needed to make a certain configuration function.  It would be fairly straightforward to add a `notify` metaparameter to restart the service at https://github.com/voxpupuli/puppet-rsyslog/blob/master/manifests/base.pp#L41-L44 . I can always catch that in my own manifest, but figured it was worth mentioning.

Alternatively, catching the need for an add-on package when a module is declared could be useful and perhaps more in line with common practices. EG, for CentOS, automatically installing *rsyslog-cypto* when encryption is enabled in the config.  Just a thought and/or warning as I ran into a problem like this across ~50 nodes at once.

For completeness, will point out that there are quite a few modules for CentOS possible:
```
$ yum search rsyslog | egrep '(support|module)' 
rsyslog-elasticsearch.x86_64 : ElasticSearch output module for rsyslog
rsyslog-gnutls.x86_64 : TLS protocol support for rsyslog
rsyslog-gssapi.x86_64 : GSSAPI authentication and encryption support for rsyslog
rsyslog-kafka.x86_64 : Provides kafka support for rsyslog
rsyslog-libdbi.x86_64 : Libdbi database support for rsyslog
rsyslog-mmnormalize.x86_64 : Log normalization support for rsyslog
rsyslog-mysql.x86_64 : MySQL support for rsyslog
rsyslog-pgsql.x86_64 : PostgresSQL support for rsyslog
rsyslog-relp.x86_64 : RELP protocol support for rsyslog
rsyslog-snmp.x86_64 : SNMP protocol support for rsyslog
rsyslog-crypto.x86_64 : Encryption support
rsyslog-mmaudit.x86_64 : Message modification module supporting Linux audit
rsyslog-mmjsonparse.x86_64 : JSON enhanced logging support
rsyslog-mmkubernetes.x86_64 : Provides the mmkubernetes module
rsyslog-mmsnmptrapd.x86_64 : Message modification module for snmptrapd generated
rsyslog-udpspoof.x86_64 : Provides the omudpspoof module
```
.... so its possible to compound this problem if one wants to support multiple modules.
