### ISSUE TITLE
Handling permissions on startup

### ISSUE THREAD

**Issue by djtecha** [voxpupuli/puppet-rsyslog#159]
Anyone have any thoughts about how this could also handle the permissions on the existing files? I know we can set new files to a user and permissions, but on boot the files are created and so you'll get a permission denied until the file gets rotated.

**Comment by igalic** [comment]
which files and permissions are we talking about, exactly?

**Comment by djtecha** [comment]
For instance `/var/log/messages` on most modern linux machines is created as 600 and owned by root:root

**Comment by igalic** [comment]
my Ubuntu laptop's `/etc/rsyslog.conf` has this stanza:

```
#
# Set the default permissions for all log files.
#
$FileOwner syslog
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022
$PrivDropToUser syslog
$PrivDropToGroup syslog
```

**Comment by djtecha** [comment]
Right but that only effects new files. What about the existing ones?

**Comment by luoymu** [comment]
how about set "$manage_confdir,"  to true?

**Comment by igalic** [comment]
what would that do?

**Comment by dhollinger** [comment]
@igalic `$manage_confdir` will tell the module that it will also be managing the Rsyslog configuration directory and its permissions. As of today, it does **not** allow users to change the owner or group on the Rsyslog configuration directory as that (usually) ends up causing issues. The permissions can be set however with the `$rsyslog::confdir_permissions` parameter.

relevant code: https://github.com/voxpupuli/puppet-rsyslog/blob/master/manifests/base.pp#L46-L69

@djtecha This module is designed to manage the Rsyslog client/server and what it does. If Rsyslog doesn't support the ability to change the permissions on an existing logfile, this module won't either. You'd have to do that with your own `file` resource(s) in your own profiles or modules.
