### ISSUE TITLE
file backup is not working correctly when existing files exist

### ISSUE THREAD

**Issue by logicminds** [voxpupuli/puppet-rsyslog#174]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.14, PE 2019.4
- Ruby: 2.4
- Distribution: RHEL 7
- Module version: 5.1.0

## How to reproduce (e.g Puppet code you use)
In site.pp have the following configuration.

```
File{
  backup => '.old'
}
use defaults for module

Add a listen.conf file in /etc/rsyslog.d/listen.conf

```
## What are you seeing
Puppet backs up this file and places in same directory.  Puppet then backs up the same file and appends another '.old' extension on top of the previous one.  After several iterations of this you end up with.

listen.conf.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
## What behaviour did you expect instead
Only a single listen.conf.old file would be reproduced.

**Comment by dhollinger** [comment]
@logicminds Sorry for the delay on this. I've been fairly busy. I'll take a look at this today or tonight and get it taken care of

**Comment by dhollinger** [comment]
@logicminds This is an issue related to the `File` resources use of `purge` and `backup` not intending to be mixed. Currently the Rsylsog module purges the `/etc/rsyslog.d` directory if the directory is managed by Puppet. As such, since the files, including backups, are being modified, Puppet sees this and backs the files up again and replaces them with an appended `.old` extension after the purge has completed.

**Comment by dhollinger** [comment]
@logicminds You need to set the value of `$rsyslog::purge_config_files` to `false` to get it to backup files correctly.

**Comment by alexjfisher** [comment]
I think you can also unset any defaults from site.pp in your rsyslog profile.

```puppet
File {
  backup => undef,
}
```
should do it.



Or possibly after you've declared the class, you can [modify the file resource.](https://puppet.com/docs/puppet/5.5/lang_resources_advanced.html#amending-attributes-with-a-resource-reference)

```puppet
File[$rsyslog::confdir] {
  backup => false,
}
```

Or if you use a puppetserver based filebucket for backup you won't have this issue either.

**Comment by alexjfisher** [comment]
Also see https://tickets.puppetlabs.com/browse/PUP-1147
