### ISSUE TITLE
Global config issue in 7.0.0

### ISSUE THREAD

**Issue by EPK-nl** [voxpupuli/puppet-rsyslog#223]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7.23.0
- Ruby: 2.5.9p229
- Distribution: RHEL 8.7
- Module version: 7.0.0

## How to reproduce (e.g Puppet code you use)

Hiera:

```yaml
rsyslog::config::global_config:
  workDirectory:
      value: '/var/lib/rsyslog'
```

But also `rsyslog::config::modules`, `rsyslog::config::actions` and `rsyslog::config::legacy_config`

## What are you seeing

In version 6.0.0 this resulted in a part in de `rsyslog.d/50_rsyslog.conf` file containing a global `workDirectory` setting.
In version 7.0.0 with exactly the same hiera data, only that global part is removed.

## What behaviour did you expect instead

No change between version 6 and 7 of this module while parsing these parameters.

## Output log

Lines with the global config setting are removed.

## Any additional information you'd like to impart

Result in our case is a disfunctional rsyslog, with SELinux reporting a lot of issues for rsyslog for not being able to open imjournal.

**Comment by emperortomato** [comment]
I'm seeing the same thing; the only way to get it to install the global config values in 7.0.0 seems to be setting `type: 'legacy'`

**Comment by kenyon** [comment]
This is due to https://github.com/voxpupuli/puppet-rsyslog/commit/58cb84e2bfe55894cadeb13cdedb0a83917bd545 (#216) somehow...
