### ISSUE TITLE
Rulesets not supported in client.pp

### ISSUE THREAD

**Issue by ayushmittal** [voxpupuli/puppet-rsyslog#58]
Hey,

Is there any reason for not supporting rulesets in client.pp? It seems to be supported only in server.pp

**Comment by dhollinger** [comment]
The only reason it's not supported client side is that it hasn't been built for the client side. When I added rulesets to the module, the only use case I'd seen is server side. Other than that, there's no reason to not support it client side.

**Comment by dhollinger** [comment]
This ticket hasn't been active in quite a while. Marking it as wont-fix and will close if no additional activity is posted.
