### ISSUE TITLE
facility not present in out put of rulsets when using - action

### ISSUE THREAD

**Issue by sean-ellicott** [voxpupuli/puppet-rsyslog#59]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: puppet/rsyslog
- Module version: 2.3.0

## What are you seeing

Facility not presented when using

rsyslog::rulesets_defaults:
  local_rules:
    parameters:
      queue.size: '1000'
      queue.type: LinkedList
    rules:
      - action:
          facility: '*.*;auth,authpriv.none'
          name: cron_logs
          type: omfile
          config:
            file: '/var/log/cron'

it generated the following

# local_rules ruleset
ruleset (name="local_rules"
  queue.size="1000"
  queue.type="LinkedList"
) {
 action(type="omfile" 
      file="/var/log/cron" )
}

found two issues... type-o in  puppet-rsyslog/templates/tasks.epp
facility is spelled faclility at Line 14 

<%- if $cfgval['facility'] == undef or '' { $facility = 'default' } else { $facility = $cfgval['faclility'] } -%>

and bad test in puppet-rsyslog/templates/tasks.epp
line 14
< %- if $cfgval['facility'] == undef or '' { $facility = 'default' } else { $facility = $cfgval['faclility'] } -%>
always returns default.
changed to
    <%- if ! $cfgval['facility'] or $cfgval['facility']  == '' { $facility = 'default' } else { $facility = $cfgval['facility'] } -%>

## What behaviour did you expect instead

i expected the foillowing

# local_rules ruleset
ruleset (name="local_rules"
  queue.size="1000"
  queue.type="LinkedList"
) {
*.*;auth,authpriv.none         action(type="omfile" file="/var/log/cron" )
}

## Any additional information you'd like to impart
this is my first time reporting ... be kind.

**Comment by dhollinger** [comment]
Confirmed bug. I'll work on it over the next couple days.

**Comment by dhollinger** [comment]
Fixed in #61
