### ISSUE TITLE
No clue how to configure a client with this module

### ISSUE THREAD

**Issue by linuxdan** [voxpupuli/puppet-rsyslog#64]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:  PE 2017.2.1
- Ruby:  2.1.9p490 (from pe-agent)
- Distribution: RHEL 7.4
- Module version:  2.3.1

## How to reproduce (e.g Puppet code you use)
class { 'rsyslog::client': }
## What are you seeing
/etc/rsyslog.d/00_client.conf
and I cannot figure out how it was generated or how to modify it to do something simple like specify the remote log server

**Comment by linuxdan** [comment]
UPDATE: I discovered I had 2 rsyslog lines in my Puppetfile - the second for saz/rsyslog - and that was where /etc/rsyslog.d/00_client.conf was coming from.

With puppet/rsyslog in place,  /etc/rsyslog.conf just has the IncludeConfig line and /etc/rsyslog.d/ is empty.
So my original question stands: How do I configure the rsyslog-client ?

**Comment by dhollinger** [comment]
@linuxdan Currently there are no default configs applied to client or server. So simply including `class { 'rsyslog::client': }` won't actually apply anything but an empty config.

You need to specify the configuration you need:

``` puppet
class { 'rsyslog::client':
  modules       => {
    'imuxsock'  => {},
    'imjournal' => {},
  },
  global_config => {
    'workDirectory'             => {
      'value' => '/var/lib/rsyslog',
    },
    'ActionFileDefaultTemplate' => {
      'value' => 'RSYSLOG_TraditionalFileFormat',
      'type'  => 'legacy',
    },
    'IncludeConfig'             => {
      'value' => '/etc/rsyslog.d/*.conf',
      'type'  => 'legacy',
    },
    'OmitLocalLogging'          => {
      'value' => 'on',
      'type'  => 'legacy',
    },
    'IMJournalStateFile'        => {
      'value' => 'imjournal.state',
      'type'  => 'legacy',
    },
  },
  legacy_config => {
    'do_not_log_private_auth_msg' => {
      'key'   => '*.info;mail.none;authpriv.none;cron.none',
      'value' => '/var/log/messages',
    },
    'auth_priv_log'               => {
      'key'   => 'authpriv.*',
      'value' => '/var/log/secure',
    },
    'mail_log'                    => {
      'key'   => 'mail.*',
      'value' => '-/var/log/maillog',
    },
    'cron_log'                    => {
      'key'   => 'cron.*',
      'value' => '/var/log/cron',
    },
    'emerg_log'                   => {
      'key'   => '*.emerg',
      'value' => ':omusrmsg:*',
    },
    'news_log'                    => {
      'key'   => 'uucp,news.crit',
      'value' => '/var/log/spooler',
    },
    'local_log'                   => {
      'key'   => 'local7.*',
      'value' => '/var/log/boot.log',
    },
  },
}
```

Will generate:

```
module(load="imuxsock")
module(load="imjournal")
global(
  workDirectory="/var/lib/rsyslog"
)
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
$IncludeConfig /etc/rsyslog.d/*.conf
$OmitLocalLogging on
$IMJournalStateFile imjournal.state

# do_not_log_private_auth_msg
*.info;mail.none;authpriv.none;cron.none                /var/log/messages

# auth_priv_log
authpriv.*                                              /var/log/secure

# mail_log
mail.*                                                  -/var/log/maillog

# cron_log
cron.*                                                  /var/log/cron

# emerg_log
*.emerg                                                 :omusrmsg:*

# news_log
uucp,news.crit                                          /var/log/spooler

# local_log
local7.*                                                /var/log/boot.log
```

The above is based on the default CentOS 7 rsyslog.conf file, though this will be saved to a `/etc/rsyslog.d/50_default.conf` file instead and the only thing that the `/etc/rsyslog.conf` will have in it is an `$IncludeConfig /etc/rsyslog.d/*.conf`.

We probably need to get some default configs added for each supported OS. This was brought over from a single maintainer and we're still working on covering everything that was missing.

Additionally, this module is primarily designed to support Rsyslog 7 and Rsyslog 8 using RainerScript (The $ConfigItem is considered legacy/deprecated by the Rsyslog project), though you can support Rsyslog < 7 configs using the `legacy_config` parameter.

**Comment by linuxdan** [comment]
Can this be accomplished in Heira files ?

**Comment by linuxdan** [comment]
RHEL 7's default rsyslog is no problem
For RHEL 6, if the package name used is "rsyslog7", you might be able to eliminate the legacy stuff

**Comment by dhollinger** [comment]
There are examples using Hiera in the README for each config type:

[Global Config example](https://github.com/voxpupuli/puppet-rsyslog/blob/master/README.md#rsyslogserverglobal_config-rsyslogclientglobal_config)

**Comment by linuxdan** [comment]
OK.
I am setting up a catalog for RHEL 6 and 7.
I want to avoid "legacy"
I would be happy to contribute some RHEL-default settings to the effort

**Comment by dhollinger** [comment]
I don't think we'll be able to avoid "legacy" 100% as there are some settings in Rsyslog that haven't been migrated over to rainerscript yet.
