### ISSUE TITLE
Add '^' (execute program) rsyslog feature to ruleset tasks

### ISSUE THREAD

**Issue by itbane** [voxpupuli/puppet-rsyslog#80]
Hi,
this is feature request to support the use of the "execute program" rsyslog feature, which is an alternative to the omprog output module.

While the omprog output module is great for programs which read from STDIN, it's not usable for software that relies on the log message being sent as an argument.

Outside of rulesets, the feature can be already used with this module via the $custom_config hash.

I have written a simple patch for this - I will attach the patch shortly.

Kind regards,
itbane

- Puppet: 5.3
- Ruby: 2.3.3
- Distribution: Debian Stretch
- Module version: 3.1.1

**Comment by dhollinger** [comment]
Added in #81
