### ISSUE TITLE
How do we configure this module for someone new to puppet

### ISSUE THREAD

**Issue by linuxphone** [voxpupuli/puppet-rsyslog#88]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: Puppet 5.5
- Ruby:
- Distribution: RedHat Eterprise Linux 6,7
- Module version:

**Comment by dhollinger** [comment]
@linuxphone I'm currently working on, well, reworking this module to be compatible with modern systems. I've had issues with some of the resources not working in new(ish) linux distributions, such as EL7 and Ubuntu 18.04.

**Comment by vidkun** [comment]
Good question. 
I've been fighting to get it to configure a simple udp listener to dump remote logs into files by ip. Even with the new "simpler" Rainerscript format, the manual implementation is rather straightforward and easy.

Yet I still can't figure out how to make this module do it.

**Comment by dhollinger** [comment]
Are there specific examples of what you are looking for? The readme docs are pretty straightforward, but do assume that you are familiar with Puppet, Hiera, and Rsyslog 8+.

**Comment by hdep** [comment]
I did have some trouble too. 
I reproduce the default debian 9 configuration with Hiera, maybe I can PR in order to add it to the folder examples ?

**Comment by dhollinger** [comment]
The key is that the module does assume that the user is quite familiar with Rsyslog 8.x configuration. Both the rainerscript format and the legacy format.

We do offer a hash called `custom_config` that allows you to pass a straight string into the template and generate config that way. It was put in to cover use-cases that don't fit what the code currently supports.

**Comment by hdep** [comment]
yeah I am not familier with rainerscript format because by default debian uses what you call legacy format.
To be honest I expect when I use a puppet module from scratch to reproduce the default configuration as the one from the package this avoid confusion imho.

**Comment by vidkun** [comment]
Same here. Limited exposure to rainerscript and as of 7.4, RHEL is still using "legacy" format. 
I'd expect module documentation to at least describe how to recreate the default config.
