### ISSUE TITLE
/etc/rsyslog.d/50_rsyslog.conf doesn't have a puppet header

### ISSUE THREAD

**Issue by hdep** [voxpupuli/puppet-rsyslog#92]
Hello,

I played a bit with your module. 
I just notice that the file generated by the module : /etc/rsyslog.d/50_rsyslog.conf does have a header like :  

`# FILE Managed by puppet`

I think this would be great to have this information. 

What do you think ?

**Comment by dhollinger** [comment]
Having a puppet header is important, I just haven't found a good way to do it. Unlike most template-based config files, the `50_rsyslog.conf` file is actually built from several puppet templates and a single template may be called during a run multiple times, thus placing that header into the file multiple times.

Any suggestions or PRs welcome. There probably needs to be some parsing added to check for the existence of the header.

**Comment by hdep** [comment]
Thank you for your feedback.
I'll try to PR, but not sure I can make it.
The code is more complicated than I am use to.

**Comment by dhollinger** [comment]
This is stale. Going to close and revisit later
