### ISSUE TITLE
 Error: Evaluation Error: Resource type not found: PrivDropToUser (file: /tmp/kitchen/manifests/site.pp, line: 141, column: 9) on node 21a40dd4ec00

### ISSUE THREAD

**Issue by juju4** [voxpupuli/puppet-rsyslog#93]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.1
- Ruby: 2.4.1p1
- Distribution: Centos/Ubuntu
- Module version: latest

## How to reproduce (e.g Puppet code you use)

```
  class { 'rsyslog::server':
    global_config   => {
        umask => {
            value => '0022',
            type => legacy,
            priority => 01, 
        },  
        PrivDropToUser => {
            value => 'syslog',
            type => legacy,
        },  
        PrivDropToGroup => {
            value => 'syslog',
            type => legacy,
        },  
        workDirectory => {
            value => '/var/spool/rsyslog',
        },  
        maxMessageSize => {
            value => '64k',
        }   
    },
```

## What are you seeing

above message

## What behaviour did you expect instead

rsyslog should be configured with given unprivileged user.
On Debian/Ubuntu, it's the default

## Output log

(centos7) https://travis-ci.org/juju4/puppet-meta-harden-linux/jobs/420572879#L2727
(bionic) https://travis-ci.org/juju4/puppet-meta-harden-linux/jobs/420572880#L3246
(xenial) https://travis-ci.org/juju4/puppet-meta-harden-linux/jobs/420572881#L3053

**Comment by dhollinger** [comment]
If you are defining that within Puppet code itself, those all have to be strings:

``` puppet
class { 'rsyslog::server':
    global_config   => {
        'umask' => {
            'value' => '0022',
            'type' => legacy,
            'priority' => 01, 
        },  
        'PrivDropToUser' => {
            'value' => 'syslog',
            'type' => legacy,
        },  
        'PrivDropToGroup' => {
            'value' => 'syslog',
            'type' => legacy,
        },  
        'workDirectory' => {
            'value' => '/var/spool/rsyslog',
        },  
        'maxMessageSize' => {
            'value' => '64k',
        }   
    },

```

As those values are not native resources or defined parameters, Puppet is going to error trying to look them up in the catalog. Instead those are values fed to the global_config.epp template and a file is generated from that.

Try replacing your above code with the sample I provided here.

**Comment by juju4** [comment]
Cool. Thanks!
Confusing that some parameters work without quotes and some don't.

**Comment by dhollinger** [comment]
That's because:

1. The documentation was built assuming the user was using hiera 4 or hiera 5, hence the YAML format.
2. Most of the parameters in this module are nested Hashes, meaning only the parameter itself is recognized as a puppet parameter.

I'm planning to add Puppet Strings documentation with parameter docs, I just haven't had time yet.
